### ISSUE TITLE
Duplicate user.name entries created in git config

### ISSUE THREAD

**Issue by khlumzeemee** [RoboPlugins/git-pair.idea#8]
Hi,
I was testing the tool today, I noticed that the git config user.name value is not updated, a separate duplicate entry is created and updated leaving the other value untouched.
Is this done on purpose?

**Comment by robert-wallis** [comment]
Actually yes.  The local project `.git/config` file is updated if you don't specify `global: true` in the .pairs file.  If `global` is true, then it updates the `~/.gitconfig` file instead.

Maybe in most paring stations global should be true by default.  But currently it is false by default.  It uses the git default, which is `git config user.name '...'` will change only the project's git config and not the `global` (user's) config.

**Comment by robert-wallis** [comment]
Possibly the plugin should show the global and local values, and show which one will be updated.  Also it should allow clearing the local value.  What do you think?

To clear the local value you might have to do this in the project folder:

``` bash
git config --unset user.name
git config --unset user.email
```

Then set `global: true` in the `.pairs` file.  And run `git config user.email` to make sure it's using the "global" (user) setting.

**Comment by khlumzeemee** [comment]
Hi,
I tried to use both global and local settings, global makes more sense and it works correctly and is easy to reset.

However what I meant is that when the global option is activated, the original user.name global value is not updated, a new user.name value is appended at the end of the global settings. So I have two entries, one with the original value and a new one with the pair.
It may be a feature, for instance if you want to know which user to default to, I was just wondering if it was done on purpose.

**Comment by robert-wallis** [comment]
Interesting, it wasn't on purpose, this plugin just calls `git config
--global user.name 'Your Name'` and git handles changing the file.  So
maybe it is a git bug.
