### ISSUE TITLE
Support for RubyMine

### ISSUE THREAD

**Issue by gabrieljoelc** [RoboPlugins/git-pair.idea#9]

**Comment by robert-wallis** [comment]
Sorry I haven't got to this in 2 years.  I bought an ultimate license, and finally was able to test in Ruby Mine 2017.3  And the plugin worked.
I need to have some event log, like docker or git, that lets you create a .pairs file if it's missing.  Version 1.4 soon to be out supports ~/.pairs and project/.pairs, but the current version 1.3 only supports project/.pairs.
